config/routes.rb
Spree::Core::Engine.routes.draw do
  resource :account, :controller => 'users' do
  	delete 'forget_credit_card'
  end
end

app/models/spree/credit_card_decorator.rb
Spree::CreditCard.class_eval do
	scope :remembered, -> {where(remember: true)}
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
	# set_callback :updating_from_params, :before, :add_remember_as_permitted_attribute

	# private
	# def add_remember_as_permitted_attribute
	# 	Spree::PermittedAttributes.source_attributes.push(:remember) unless Spree::PermittedAttributes.source_attributes.include?(:remember)
	# end
end

app/controllers/spree/checkout_controller_decorator.rb
Spree::CheckoutController.class_eval do 
	alias_method :orginal_before_payment, :before_payment

	def before_payment
		Spree::PermittedAttributes.source_attributes.push(:remember) unless Spree::PermittedAttributes.source_attributes.include?(:remember)
		orginal_before_payment
		@payment_sources = @payment_sources.remembered if @payment_sources.present?
	end
end

app/controllers/spree/users_controller_decorator.rb
Spree::UsersController.class_eval do
	prepend_before_filter :load_object, :only => [:show, :edit, :update, :forget_credit_card]

	def forget_credit_card
		credit_card = @user.credit_cards.remembered.find(params[:credit_card_id])
		if credit_card && credit_card.toggle!(:remember)
			flash[:notice] = I18n.t('memorable_payment_profile.credit_card_forgotten')
		else
			flash[:error] = I18n.t('memorable_payment_profile.failed_to_forget_credit_card')
		end
		redirect_to :back
	end
end

app/views/spree/users/_credit_cards.html.erb
<br/>
<div data-hook="credit_card_account_my_orders" class="account-my-orders">
	<h3><%= t(:my_credit_cards) %></h3>
	<% if try_spree_current_user.try(:credit_cards).present? && !try_spree_current_user.credit_cards.remembered.blank? %>
	<table id="user_credit_cards">
	  <tbody>
	    <% try_spree_current_user.credit_cards.remembered.each do |credit_card| %>
	    <tr class="<%= cycle('even', 'odd') %>">
	      <td>XXXX-XXXX-XXXX-<%= credit_card.last_digits %></td>
	      <td><%= credit_card.month %>&nbsp;/&nbsp;<%= credit_card.year %></td>
	      <td>
	        <%= link_to Spree.t(:remove), forget_credit_card_account_path(credit_card_id: credit_card.id), { :method => :delete, data: {:confirm => Spree.t(:are_you_sure)} } %>
	      </td>
	    </tr>
	    <% end %>
	  </tbody>
	</table>
	<% else %>
	<div id="users-address-list-empty">
	  <%= I18n.t('memorable_payment_profile.no_credit_cards_on_file') %>
	</div>
	<% end %>
	<div id="users-address-list-empty">
	  <%= I18n.t('memorable_payment_profile.add_a_credit_card') %>
	</div>
</div>